version: '3.4'

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - server
    ports:
      - 3000:3000

  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - 4000:4000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
