version: '3.4'

services:
  
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
      - DB_PATH=="mongodb://mongo:27017/twitts"
    ports:
      - 4000:4000
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
